INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (1, "Catrina", "Collom", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/1.jpg?raw=true", "Business", "catrina.collom@gmail.com", "rV&TKF", "NY", 80, "Spanish", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution.", "Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. ", "Monday, Friday", 5, "Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive e-commerce via process-centric outside the box thinking. Completely pursue scalable customer service through sustainable potentialities.");

INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (2, "Josue", "Brenneman", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/2.jpg?raw=true", "Health", "josue.brenneman@gmail.com", "Eem*qA", "Miami", 100, "Spanish", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "Bring to the table win-win survival strategies to ensure proactive domination.", "Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.", "Tuesday, Friday", 4, "Proactively envisioned multimedia based expertise and cross-media growth strategies. Seamlessly visualize quality intellectual capital without superior collaboration and idea-sharing. Holistically pontificate installed base portals after maintainable products.");

INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (3, "Felix", "Wemmer", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/3.jpg?raw=true", "Leadership", "felix.wemmer@gmail.com", "mASONO", "Los Angeles", 120, "English, Spanish", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.", "Bring to the table win-win survival strategies to ensure proactive domination.", "Saturday, Sunday", 3, "Objectively innovate empowered manufactured products whereas parallel platforms. Holisticly predominate extensible testing procedures for reliable supply chains. Dramatically engage top-line web services vis-a-vis cutting-edge deliverables.");

INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (4, "Farrah", "Yelverton", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/4.jpg?raw=true", "Relationship", "farrah.yelverton@gmail.com", "hPPCqW", "CDMX", 50, "English, Spanish", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. ", "At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution.", "Monday", 5, "Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service.");

INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (5, "Gemma", "Dubrei", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/5.jpg?raw=true", "Career", "gemma.dubrei@gmail.com", "sq!lzF", "NY", 75, "French", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test.", "User generated content in real-time will have multiple touchpoints for offshoring.", "Tuesday, Friday", 4, "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.");

INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (6, "Val", "Bork", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/6.jpg?raw=true", "Sports", "val.bork@gmail.com", "qRAS$c", "NY", 150, "German, English, French", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "User generated content in real-time will have multiple touchpoints for offshoring.", "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test.", "Friday, Sunday", 5, "Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration.");

INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (7, "Arturo", "Bellevil", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/7.jpg?raw=true", "Business", "arturo.bellevil@gmail.com", "cKUWeb", "CDMX", 300, "Spanish, English", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution.", "Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. ", "Monday, Friday", 4, "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line.");

INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (8, "Liliana", "Paradis", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/8.jpg?raw=true", "Health", "liliana.paradis@gmail.com", "zRtjBj", "Paris", 500, "French, Chinese", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "Bring to the table win-win survival strategies to ensure proactive domination.", "Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.", "Tuesday, Friday", 3, "Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.");

INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (9, "Carisa", "Laxton", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/9.jpg?raw=true", "Leadership", "carisa.laxton@gmail.com", "ACtExt", "London", 90, "English", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.", "Bring to the table win-win survival strategies to ensure proactive domination.", "Saturday, Sunday", 5, "Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.");

INSERT INTO coaches (id, firstname, lastname, picture, category, email, password, location, fee, languages, linkedin, twitter, website, personalstatement, education, opendays, ratings, testimonials)
VALUES (10, "Tom", "Steffield", "https://github.com/humberto24/Project-3/blob/sandra/client/public/images/coaches/10.jpg?raw=true", "Leadership", "tom.steffield@gmail.com", "&Sgj$v", "London", 450, "English, Chinese", "https://www.linkedin.com/", "https://twitter.com/", "https://www.google.com/", "Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. ", "At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution.", "Wednesday", 4, "At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.");

